### ISSUE TITLE
Plan to null-safety

### ISSUE THREAD

**Issue by leedstyh** [gyrdym/ml_linalg#103]
Hi, thanks for this great project and do you have some plan to null-safety?

**Comment by gyrdym** [comment]
@leedstyh hi @leedstyh thank you very much for your attention to the project. Yes, I have plans to migrate the codebase to null-safety basis, It's a high priority task. Just keep tracking the updates of the lib :)

**Comment by leedstyh** [comment]
thanks @gyrdym , thats great
