### ISSUE TITLE
Invalid Json String returned

### ISSUE THREAD

**Issue by gnudles** [gyrdym/ml_linalg#112]
The method toJson returns naked keys and values (without " around them)

**Comment by gyrdym** [comment]
@gnudles hi, thank you for creating the issue! It is by design - `toJson` returns a serializable structure, not a string. It is a responsibility of a consumer to convert the structure to string. If anything, the `toJson` result is ready to be encoded.

**Comment by gnudles** [comment]
Yeah, I looked at implementation and noticed it just now, you are right. Great library, thank you.
