### ISSUE TITLE
Galois Field calculations, XOR operation!

### ISSUE THREAD

**Issue by a7mdragab** [gyrdym/ml_linalg#128]
Hello,
Great work., thanks for your effort.

Can this library help me with calculating operations like these?
![image](https://user-images.githubusercontent.com/30768001/181619440-5d520ab5-af57-49bd-b2f8-a469ae133621.png)

Also, Does it have an xor operation between vectors?
Thanks in advance

**Comment by gyrdym** [comment]
Hi @a7mdragab!

Thank you for your interest in the lib!

No, there is no such functionality, but I will add it to my long term plans, thank you.
