### ISSUE TITLE
Question: Vector difference between ml_linalg and vector_math

### ISSUE THREAD

**Issue by shtse8** [gyrdym/ml_linalg#165]
Thanks for your detailed readme to explain SIMD in details. It's very attractive to perform SIMD to calculate Vector and Matrix to speed up the performance.
 There are many projects are using Google vector classes which provided many tools to perform computation. I know they are using Float64List as underlying storage and would like to know what is the difference between this and their project. 
Thanks.

**Comment by gyrdym** [comment]
@shtse8 hello!

First of all, thanks for your interest in the library! 

That's a good question. Indeed, at first glance, both libraries look the same. But `vector_math` is limited to only vectors of length four at max - I suppose this library is designed for graphic geometry:

```dart
final vector = Vector4.all(4.0); // if you print the variable, it will output only four values
``` 

`ml_linalg` offers vectors of potentially infinite length; for instance, you may create a vector of length 10000:

```dart
final vector = Vector.randomFilled(10000);
```

Also, `ml_lianlg` is designed mainly for statistics and linear algebra for machine learning.

**Comment by shtse8** [comment]
Supporting unlimited length is awesome!

Does the Google Library have SIMD support? Whether SIMD is being used in their implementation, I wonder.

This is the major reason I'm seeking for a replacement algebra library that supports SIMD.

More differences should be mentioned, in my opinion, on the readme page.

I believe that because `vector_math` was created by Google, people are adopting it mindlessly. Yet the project isn't moving forward.

I hope this initiative develops quickly.

**Comment by gyrdym** [comment]
@shtse8 Google library uses SIMD under the hood. 

Thanks for your advice! I definitely need to add the differences to the README.

**Comment by gyrdym** [comment]
Added differences to the README
