### ISSUE TITLE
Typo in min() description

### ISSUE THREAD

**Issue by MELICI0US** [gyrdym/ml_linalg#167]
https://github.com/gyrdym/ml_linalg/blob/6a5c07e436c8334e6fdfd3cdd0ec18a05949b7e6/lib/vector.dart#L372

Says min() returns max element. I would hope it returns min element.

**Comment by gyrdym** [comment]
Sure, you're right. I'll fix it soon.

**Comment by gyrdym** [comment]
Fixed here - https://github.com/gyrdym/ml_linalg/pull/168
