### ISSUE TITLE
Support matrix transform methods

### ISSUE THREAD

**Issue by II11II** [gyrdym/ml_linalg#169]
I could not find the syntax sugar api:
To take m-to-n vectors from Matrix
To remove m-to-n vectors from Matrix

**Comment by II11II** [comment]
f.e.
```
void main() {
  final matrix = Matrix.fromList([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
  ]);

  final slice = matrix.slice(1, 3, 0, 2);
  final subMatrix=matrix.subMatrix(1,2,2);

  print(slice);
  // [[4.0, 5.0], [7.0, 8.0]]
   print(subMatrix);
     // [ [4, 5, 6],
   // [7, 8, 9],]
}

```

**Comment by gyrdym** [comment]
@II11II Hello! Again, thank you for your interest in the lib. Indeed, there is no such API. Though it looks valuable, I'll consider adding such functionality.

**Comment by gyrdym** [comment]
@II11II But you may use [this](https://pub.dev/documentation/ml_linalg/latest/matrix/Matrix/sample.html) method in Matrix class instead
