### ISSUE TITLE
Worse performance in Flutter release vs Flutter debug

### ISSUE THREAD

**Issue by laurenspriem** [gyrdym/ml_linalg#175]
We're using your package in our flutter app to compare embeddings, and we're noticing that it's a lot slower in release mode versus debug mode. 

To give concrete numbers, comparing 10K embeddings using Vector class takes only 11 seconds in debug mode but 56 seconds in release mode. 

I'm using the following simple code to benchmark:
```dart
Future<int> clusteringTimeInSeconds(int embeddingAmount) async {
  // Create 10K fake embeddings
  final embeddings = List.generate(embeddingAmount, (_) => _createRandomEmbedding());
  final List<Vector> vectorEmbeddings =
      embeddings.map((embedding) => Vector.fromList(embedding)).toList();

  final startTime = DateTime.now();
  for (int i = 1; i < embeddings.length; i++) {
    if ((i + 1) % 250 == 0) {
      debugPrint("Processed ${i + 1} embeddings");
    }
    final vectorEmbedding1 = vectorEmbeddings[i];
    double closestDistance = double.infinity;
    for (int j = i - 1; j >= 0; j--) {
      final double distance = 1 - vectorEmbedding1.dot(vectorEmbeddings[j]);
      if (distance < closestDistance) {
        closestDistance = distance;
      }
    }
  }
  final endTime = DateTime.now();
  final vectorClusteringTime = endTime.difference(startTime).inSeconds;

  return vectorClusteringTime;
}
```
Please see [this repo](https://github.com/laurenspriem/flutter_release_performance/blob/79fa1f28b09560c84782a97b0894f6a555ef26b6/lib/main.dart) for the full code of this MRE.

**Comment by gyrdym** [comment]
Hello,

I will take a look soon.

**Comment by gyrdym** [comment]
@laurenspriem flutter release mode utilises AOT (Ahead-Of-Time) compilation. AOT compilation doesn't use some optimisation techniques, compared to JIT (Just-In-Time) compilation, which is used in debug mode. 

I'll try to force compiler to use some optimisations for AOT as i does in JIT mode.

**Comment by gyrdym** [comment]
@laurenspriem, apparently, this is a Dart SDK issue. I've reached out to the Dart team to look into the problem and am waiting for their response. In the meantime, I'll try to use C-language FFI to provide good performance in Flutter's release mode.

**Comment by gyrdym** [comment]
@laurenspriem good news! Dart team found a missing optimization for AoT compilation (which is used in flutter release mode). The fix will be delivered soon to Dart SDK - apparently, we will need to update Dart version to make it work

**Comment by laurenspriem** [comment]
That's great to hear! Thank you for taking this issue so seriously.

I'm curious about the exact optimization. Is there perhaps a Dart issue or response you could point me towards?

**Comment by gyrdym** [comment]
I think the performance will be comparable to debug mode. There is an [issue](https://github.com/dart-lang/sdk/issues/53662), but it seems more inactive than active. I asked about the problem on Twitter [here](https://x.com/ilgyrd/status/1796918025599201287) and got a response in the thread.

**Comment by gyrdym** [comment]
The fix is in the main branch - https://github.com/dart-lang/sdk/commit/e0710a5cc61a52b73b07a616e2c611ef79b57a60
As far as I understand, it's in the dev-channel (https://github.com/dart-lang/sdk/releases/tag/3.5.0-236.0.dev)

**Comment by gyrdym** [comment]
@laurenspriem

Hi,

I have tested the Dart SDK 3.5.0, and I found that the performance in AoT compilation is even better—6 seconds in AoT versus 9 seconds in JIT. 

Now you can definitely use ml_linalg in any Flutter app without sacrificing performance.

**Comment by gyrdym** [comment]
@laurenspriem 

keep in mind that you need to switch to Dart SDK 3.5.0
